In [8]:
import tensorflow as tf
import pymysql as db
import pandas as pd

In [9]:
conn = db.connect(host='192.168.2.88', port=3306, user='zach', passwd='1qaz!QAZ', db='old')

In [10]:
query_action = 'SELECT * FROM old.matomo_log_action'

In [11]:
df_action = pd.read_sql_query(query_action, conn)

In [12]:
df_action

,idaction,name,hash,type,url_prefix
0,1,StrataGem by Rigil,469154411,4,NaN
1,2,206.205.101.39:8080/app/,787866642,1,0.0
2,3,localhost:4200/,3504196112,1,0.0
3,4,206.205.101.52:8081/app/,699733267,1,0.0
4,5,10.22.16.181:8080/app/,1869514949,1,0.0
5,6,Login/MenuView,1628449468,4,NaN
6,7,com.rigil.matchgame1/Login/MenuView,513793483,1,0.0
7,8,menu,2097494675,4,NaN
8,9,com.architdhupar.sganalyticsexample/menu,3750448386,1,0.0
9,10,com.rigil.matchgame1/,1833139562,10,0.0
10,11,LeaderBoardAction,1917778110,11,NaN
11,12,TestCategory,1325569498,10,NaN
12,13,LeaderBoard,1601434240,12,NaN
13,14,ReviewAction,3253179099,11,NaN
14,15,Review,2129626352,12,NaN
15,16,EvaluateAction,3167185038,11,NaN
16,17,Evaluate,2012375262,12,NaN
17,18,com.rigil.matchgame/Login/MenuView,1757713057,1,0.0
18,19,com.rigil.matchgame/,1811729535,10,0.0
19,20,EvalauteAction,1672370785,11,NaN
20,21,Evalaute,3014042554,12,NaN
21,22,Home,3521422318,4,NaN
22,23,com.rigil.matchgame/Home,409234017,1,0.0
23,24,Home/Evalaute,2508116631,4,NaN
24,25,com.rigil.matchgame/Home/Evalaute,4153074843,1,0.0
25,26,Home/LeaderBoard,3519690052,4,NaN
26,27,com.rigil.matchgame/Home/LeaderBoard,3944508210,1,0.0
27,28,Home/Review,3827282609,4,NaN
28,29,com.rigil.matchgame/Home/Review,369456840,1,0.0
29,30,Home/Match,4095679872,4,NaN
...,...,...,...,...,...
161,162,com.rigil.aircraftvector/Home/Relative%20headi...,3863886556,1,0.0
162,163,Relative headings-Level3,4117589733,12,NaN
163,164,Relative headings-Challenge,3801376523,12,NaN
164,165,Simulated Aircraft-Level1,1194529966,12,NaN
165,166,Home/Simulated Aircraft/2,3368860138,4,NaN
166,167,com.rigil.aircraftvector/Home/Simulated%20Airc...,4268770041,1,0.0
167,168,Simulated Aircraft-Level2,3728360724,12,NaN
168,169,Simulated Aircraft-Level3,2839377282,12,NaN
169,170,Home/Compass Headings/Challenge,1094564073,4,NaN
170,171,com.rigil.aircraftvector/Home/Compass%20Headin...,1447503551,1,0.0
171,172,Home/Wind Effects,2837790282,4,NaN
172,173,com.rigil.aircraftvector/Home/Wind%20Effects,274927676,1,0.0
173,174,Home/Wind Effects/1,3387701673,4,NaN
174,175,com.rigil.aircraftvector/Home/Wind%20Effects/1,1818186576,1,0.0
175,176,Wind Effects-Level1,2711386501,12,NaN
176,177,Home/Simulated Aircraft/Level1,2811125127,4,NaN
177,178,com.rigil.aircraftvector/Home/Simulated%20Airc...,2498869106,1,0.0
178,179,Pick image,2033750258,10,NaN
179,180,Pick Pronunciation,3358487078,10,NaN
180,181,Mission-1,2459742241,10,NaN
181,182,NumberOfMoves,1813465589,12,NaN
182,183,Success,2696799790,11,NaN
183,184,Mission-1,2459742241,12,NaN
184,185,Mission-2,194371995,10,NaN
185,186,Home/Mision 2,2324131392,4,NaN
186,187,com.rigil.advancedaircraftvector/Home/Mision%202,1228678282,1,0.0
187,188,Home/Mision 3,4253048534,4,NaN
188,189,com.rigil.advancedaircraftvector/Home/Mision%203,1044059164,1,0.0
189,190,Mission-3,2089996557,10,NaN
190,191,localhost:4200/app/,212160010,1,0.0

In [14]:
df_action_name = df_action.groupby(['name']).agg({'name': 'count'}).sort_values(by='name', ascending=False)

/home/zachclem/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: 'name' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version
  """Entry point for launching an IPython kernel.

In [15]:
df_action_name

                                                    name
name
Mission-1                                              2
Mission 1                                              2
Evaluate                                               2
10.22.16.181:8080/app/                                 1
com.rigil.advancedaircraftvector/Home/Mision%202       1
Tile                                                   1
Unsuccessful                                           1
Wind Effects-Level1                                    1
WordGame                                               1
com.architdhupar.sganalyticsexample/menu               1
com.rigil.advancedaircraftvector/                      1
com.rigil.advancedaircraftvector/Home                  1
com.rigil.advancedaircraftvector/Home/Mision%201       1
com.rigil.advancedaircraftvector/Home/Mision%204       1
com.rigil.advancedaircraftvector/Home/Mision%203       1
Success                                                1
com.rigil.advancedaircraftvector/Home/Mision%205       1
com.rigil.advancedaircraftvector/Home/Reference        1
com.rigil.aircraftvector/                              1
com.rigil.aircraftvector/Home                          1
com.rigil.aircraftvector/Home/Absolute%20Headings      1
com.rigil.aircraftvector/Home/Absolute%20Headin...     1
com.rigil.aircraftvector/Home/Absolute%20Headin...     1
com.rigil.aircraftvector/Home/Aircraft%20Types         1
TestCategory                                           1
StrataGem by Rigil                                     1
com.rigil.aircraftvector/Home/Closest%20Headings       1
Simulated Aircraft-Level3                              1
NumberOfMoves                                          1
Pick 3 Letter ID                                       1
...                                                  ...
MatchAll                                               1
MatchPro                                               1
Mission-2                                              1
Mission-3                                              1
N90                                                    1
N90 / Aircraft Livery                                  1
Home/Review                                            1
Home/Relative headings/1                               1
Home/Compass Headings/Level1                           1
Home/Relative headings                                 1
Home/Evalaute                                          1
Home/Info                                              1
Home/LeaderBoard                                       1
Home/Match                                             1
Home/Match Pro                                         1
Home/Mision 1                                          1
Home/Mision 2                                          1
Home/Mision 3                                          1
Home/Mision 4                                          1
Home/Mision 5                                          1
Home/Pick 3 Letter ID                                  1
Home/Pick Callsign                                     1
Home/Pick Hindi Words                                  1
Home/Pick Livery                                       1
Home/Pick Name                                         1
Home/Pick Pronunciation                                1
Home/Pick attachment                                   1
Home/Pick image                                        1
Home/Reference                                         1
menu                                                   1

[188 rows x 1 columns]

In [17]:
df_action_type = df_action.groupby(['type']).agg({'type': 'count'}).sort_values(by='type', ascending=False)

/home/zachclem/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: 'type' is both an index level and a column label.
Defaulting to column, but this will raise an ambiguity error in a future version
  """Entry point for launching an IPython kernel.

In [19]:
df_action_type

      type
type
1       62
4       46
12      39
10      30
11      14

In [28]:
df_action[df_action['type'] == 11]

     idaction               name        hash  type  url_prefix
10         11  LeaderBoardAction  1917778110    11         NaN
13         14       ReviewAction  3253179099    11         NaN
15         16     EvaluateAction  3167185038    11         NaN
19         20     EvalauteAction  1672370785    11         NaN
31         32          Incorrect   119908286    11         NaN
34         35            Correct    78467623    11         NaN
42         43          InCorrect  3365445154    11         NaN
45         46          Completed  3087654605    11         NaN
56         57           Complete  3138499189    11         NaN
58         59         Incomplete   851513696    11         NaN
137       138                N90  2904081614    11         NaN
141       142       Unsuccessful  1527251898    11         NaN
144       145       Simple Hindi  3480110031    11         NaN
182       183            Success  2696799790    11         NaN

In [27]:
df_action[df_action['type'] == 12]

     idaction                              name        hash  type  url_prefix
12         13                       LeaderBoard  1601434240    12         NaN
14         15                            Review  2129626352    12         NaN
16         17                          Evaluate  2012375262    12         NaN
20         21                          Evalaute  3014042554    12         NaN
33         34    N90/Callsign &amp; 3 Letter ID  2987726107    12         NaN
46         47          Simple Hindi/Basic Words  2841467912    12         NaN
61         62               N90/Aircraft Livery  1959198455    12         NaN
68         69           Compass Headings-Level3  3737817273    12         NaN
72         73           Compass Headings-Level1   818213269    12         NaN
79         80          Absolute Headings-Level2  1988316574    12         NaN
84         85          Relative headings-Level1   459476937    12         NaN
89         90           Closest Headings-Level2   304230513    12         NaN
94         95             Aircraft Types-Level1  2632213129    12         NaN
100       101                         Mission 1   657641068    12         NaN
119       120             N90/Aircraft Carriers  2778606191    12         NaN
126       127        Simple Hindi / Basic Words  2318167100    12         NaN
127       128             N90 / Aircraft Livery  2940771151    12         NaN
133       134        Callsign &amp; 3 Letter ID  2829389562    12         NaN
138       139                   Aircraft Livery  2343142852    12         NaN
139       140           Compass Headings-Level2  2848825391    12         NaN
140       141        Compass Headings-Challenge  1170164364    12         NaN
143       144                                 5  2226203566    12         NaN
145       146                       Basic Words   375435223    12         NaN
146       147  N90 / Callsign &amp; 3 Letter ID  2507404414    12         NaN
151       152           Closest Headings-Level1  2334876107    12         NaN
152       153           Closest Headings-Level3  1696923879    12         NaN
153       154        Closest Headings-Challenge  1651063934    12         NaN
156       157          Absolute Headings-Level1  4018805796    12         NaN
157       158          Absolute Headings-Level3    25459976    12         NaN
158       159       Absolute Headings-Challenge  4220993346    12         NaN
159       160          Relative headings-Level2  2188009075    12         NaN
162       163          Relative headings-Level3  4117589733    12         NaN
163       164       Relative headings-Challenge  3801376523    12         NaN
164       165         Simulated Aircraft-Level1  1194529966    12         NaN
167       168         Simulated Aircraft-Level2  3728360724    12         NaN
168       169         Simulated Aircraft-Level3  2839377282    12         NaN
175       176               Wind Effects-Level1  2711386501    12         NaN
181       182                     NumberOfMoves  1813465589    12         NaN
183       184                         Mission-1  2459742241    12         NaN